name: Check Python Code Style (Black)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black-check:
    name: Run Black code formatter check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Black
        run: pip install black==25.1.0

      - name: Run Black check
        run: black --check .